repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21 # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
